# **DATA MANIPULATION**

Data manipulation is the process of modifying, organizing, arranging, and transforming data to make it useful for analysis and decision-making.

#### EXAMPLE:
Create a Sample Dataset.

In [18]:
import pandas as pd

fruits = pd.DataFrame({
    "Fruit_ID": [101, 102, 103, 104, 105, 105],
    "NAME": ["Grapes", "Muskmelon", "Watermelon", "Strawberry", "Raspberry", "Cranberry"],
    "QUALITY": ["Fresh", "Ripe", "Rotten", "Fresh", "Fresh", "Ripe"],
    "TASTE": ["Sour", "Sweet", "Sweet", "Sour", "Sweet", "sweet"],
    "QUANTITY": [11, 2, 3, 50, 41, 77]
})

print("FRUITS DATA")
print(fruits)

FRUITS DATA
   Fruit_ID        NAME QUALITY  TASTE  QUANTITY
0       101      Grapes   Fresh   Sour        11
1       102   Muskmelon    Ripe  Sweet         2
2       103  Watermelon  Rotten  Sweet         3
3       104  Strawberry   Fresh   Sour        50
4       105   Raspberry   Fresh  Sweet        41
5       105   Cranberry    Ripe  sweet        77

## RENAME COLUMNS

### DEFINITION:
RENAME COLUMNS means changing the name of an existing column in a table without changing the data stored in it.

In SQL, the syntax depends on the database system.

#### EXAMPLE:
Renaming Column name Percentage to Quantity.

In [19]:
fruits.rename(columns={"QUANTITY":"PERCENTAGE"})

   Fruit_ID        NAME QUALITY  TASTE  PERCENTAGE
0       101      Grapes   Fresh   Sour          11
1       102   Muskmelon    Ripe  Sweet           2
2       103  Watermelon  Rotten  Sweet           3
3       104  Strawberry   Fresh   Sour          50
4       105   Raspberry   Fresh  Sweet          41
5       105   Cranberry    Ripe  sweet          77

## DROP ROWS

### DEFINITION:

Drop Rows means removing unwanted rows (records) from a dataset or table. In SQL, we use the DELETE command to remove specific rows based on a condition.

#### EXAMPLE:

Deleting row

In [20]:
fruits.drop(1)

   Fruit_ID        NAME QUALITY  TASTE  QUANTITY
0       101      Grapes   Fresh   Sour        11
2       103  Watermelon  Rotten  Sweet         3
3       104  Strawberry   Fresh   Sour        50
4       105   Raspberry   Fresh  Sweet        41
5       105   Cranberry    Ripe  sweet        77

* Deleting Multiple Rows.

In [21]:
fruits.drop([1,3])

   Fruit_ID        NAME QUALITY  TASTE  QUANTITY
0       101      Grapes   Fresh   Sour        11
2       103  Watermelon  Rotten  Sweet         3
4       105   Raspberry   Fresh  Sweet        41
5       105   Cranberry    Ripe  sweet        77

## DROP COLUMNS

### DEFINITION:
Drop Columns means removing an unwanted column from a table or dataset. In SQL, the ALTER TABLE command with DROP COLUMN is used to remove a column and all its stored values.

#### EXAMPLE:
Deleting column from dataset.

## DROP COLUMNS

### DEFINITION:
Drop Columns means removing an unwanted column from a table or dataset. In SQL, the ALTER TABLE command with DROP COLUMN is used to remove a column and all its stored values.

#### EXAMPLE:

Deleting Column from Dataset.

In [22]:
fruits.drop(columns=["QUANTITY"])

   Fruit_ID        NAME QUALITY  TASTE
0       101      Grapes   Fresh   Sour
1       102   Muskmelon    Ripe  Sweet
2       103  Watermelon  Rotten  Sweet
3       104  Strawberry   Fresh   Sour
4       105   Raspberry   Fresh  Sweet
5       105   Cranberry    Ripe  sweet

## INSERT COLUMNS

### DEFINITION:
Insert Columns means adding a new column to an existing table or dataset. In SQL, the ALTER TABLE command with ADD COLUMN is used to create a new column.

#### EXAMPLE:
Adding new Column to Dataset.

In [26]:
fruits.insert(5, "STATUs", ['Shipped', 'Packed', 'Delivered', 'Cancelled', 'Returned', 'Preparing'])
print(fruits)

   Fruit_ID        NAME QUALITY  TASTE  QUANTITY     STATUs     STATUS
0       101      Grapes   Fresh   Sour        11    Shipped    Shipped
1       102   Muskmelon    Ripe  Sweet         2     Packed     Packed
2       103  Watermelon  Rotten  Sweet         3  Delivered  Delivered
3       104  Strawberry   Fresh   Sour        50  Cancelled   Canceled
4       105   Raspberry   Fresh  Sweet        41   Returned   Returned
5       105   Cranberry    Ripe  sweet        77  Preparing  Preparing

## ASSIGN()

### DEFINITION:
ASSIGN means giving a value to a variable or creating a new column by assigning values or calculations to it. In data manipulation using Python Pandas, assignment is commonly used to add a new column or update an existing column.

#### EXAMPLE:

In [30]:
FRUITS_new = fruits.assign(
    Pass=fruits["QUALITY"] == 'Fresh'
)
print("UPDATED FRUITS LIST is: ")
print(FRUITS_new)

UPDATED FRUITS LIST is:
   Fruit_ID        NAME QUALITY  TASTE  QUANTITY     STATUs     STATUS   Pass
0       101      Grapes   Fresh   Sour        11    Shipped    Shipped   True
1       102   Muskmelon    Ripe  Sweet         2     Packed     Packed  False
2       103  Watermelon  Rotten  Sweet         3  Delivered  Delivered  False
3       104  Strawberry   Fresh   Sour        50  Cancelled   Canceled   True
4       105   Raspberry   Fresh  Sweet        41   Returned   Returned   True
5       105   Cranberry    Ripe  sweet        77  Preparing  Preparing  False

## APPLY()

### DEFINITION:
apply() is a function in Python Pandas used to apply a function to each element in a Series or along rows or columns of a DataFrame.

#### EXAMPLE:

In [42]:
fruits["NAME"].apply(str.upper)

0        GRAPES
1     MUSKMELON
2    WATERMELON
3    STRAWBERRY
4     RASPBERRY
5     CRANBERRY
Name: NAME, dtype: str

## MAP()

### DEFINITION:
map() is a function in Python Pandas used to replace or transform each value in a Series (a single column) using a function or a dictionary.

#### EXAMPLE:

In [43]:
grade_map = {
    "Shipped": "Excellent",
    "Packed": "Good",
    "Delivered": "Average",
    "Cancelled": "Worst",
    "Returned": "Fine",
    "Preparing": "Going ON"
}

fruits["RATING"] = fruits["STATUs"].map(grade_map)

print(fruits)

   Fruit_ID        NAME QUALITY  TASTE  QUANTITY     STATUs     STATUS  \
0       101      Grapes   Fresh   Sour        11    Shipped    Shipped
1       102   Muskmelon    Ripe  Sweet         2     Packed     Packed
2       103  Watermelon  Rotten  Sweet         3  Delivered  Delivered
3       104  Strawberry   Fresh   Sour        50  Cancelled   Canceled
4       105   Raspberry   Fresh  Sweet        41   Returned   Returned
5       105   Cranberry    Ripe  sweet        77  Preparing  Preparing

      RATING
0  Excellent
1       Good
2    Average
3      Worst
4       Fine
5   Going ON

## REPLACE()

### DEFINITION:
replace() is a function in Python Pandas used to replace existing values in a DataFrame or Series with new values.

#### EXAMPLE:

In [45]:
fruits = fruits.replace({
    "NAME":{
        "Grapes": "KiWi",
        "Muskmelon": "Dragon"
    }
})

print(fruits)

   Fruit_ID        NAME QUALITY  TASTE  QUANTITY     STATUs     STATUS  \
0       101        KiWi   Fresh   Sour        11    Shipped    Shipped
1       102      Dragon    Ripe  Sweet         2     Packed     Packed
2       103  Watermelon  Rotten  Sweet         3  Delivered  Delivered
3       104  Strawberry   Fresh   Sour        50  Cancelled   Canceled
4       105   Raspberry   Fresh  Sweet        41   Returned   Returned
5       105   Cranberry    Ripe  sweet        77  Preparing  Preparing

      RATING
0  Excellent
1       Good
2    Average
3      Worst
4       Fine
5   Going ON

## DUPLICATE HANDLING

### DEFINITION:
Duplicate handling is the process of identifying and removing repeated records from a dataset to maintain data accuracy and avoid unnecessary repetition.

#### EXAMPLE:
* **DUPLICATE**

In [47]:
fruits.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

* **COUNT Duplicate Rows**

In [50]:
fruits.duplicated().sum()

np.int64(0)

* **REMOVE Duplicate Rows**

In [51]:
fruits.drop_duplicates()

,Fruit_ID,NAME,QUALITY,TASTE,QUANTITY,STATUs,STATUS,RATING
0,101,KiWi,Fresh,Sour,11,Shipped,Shipped,Excellent
1,102,Dragon,Ripe,Sweet,2,Packed,Packed,Good
2,103,Watermelon,Rotten,Sweet,3,Delivered,Delivered,Average
3,104,Strawberry,Fresh,Sour,50,Cancelled,Canceled,Worst
4,105,Raspberry,Fresh,Sweet,41,Returned,Returned,Fine
5,105,Cranberry,Ripe,sweet,77,Preparing,Preparing,Going ON