# **GROUPING & AGGREGATION**

* 1. **GROUPING**
Grouping is the process of organizing data into groups based on common values in one or more columns.

* 2. **AGGREGATION**
Aggregation is the process of summarizing data using calculations such as sum, average, count, minimum, and maximum.

In [4]:
import pandas as pd

employees = pd.DataFrame({
    "Employee_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Bhaskar","Balu","Baruni","Bhuvesh","Barath","Brindha","Beema","Bushan"],
    "Department": ["AI","ML","AI","DS","ML","DS","AI","ML"],
    "Gender": ["Male","Male","Female","Male","Male","Female","Female","Male"],
    "Marks": [76,88,99,94,82,72,89,88],
    "Age": [22,23,21,24,22,23,21,21]
})

print(employees)

   Employee_ID     Name Department  Gender  Marks  Age
0          101  Bhaskar         AI    Male     76   22
1          102     Balu         ML    Male     88   23
2          103   Baruni         AI  Female     99   21
3          104  Bhuvesh         DS    Male     94   24
4          105   Barath         ML    Male     82   22
5          106  Brindha         DS  Female     72   23
6          107    Beema         AI  Female     89   21
7          108   Bushan         ML    Male     88   21

## GROUPBY()

### DEFINITION:
groupby() is a Pandas function used to group data based on common values in a column, so that calculations can be performed on each group separately.

In [5]:
employees.groupby("Department")["Marks"].mean()

Department
AI    88.0
DS    83.0
ML    86.0
Name: Marks, dtype: float64

## AGG()

### DEFINITION:
agg() is a Pandas function used to perform one or more aggregation operations, such as sum, mean, count, minimum, and maximum, on data.

#### EXAMPLE:

In [6]:
employees.groupby("Department")["Marks"].agg(
    ["mean","max","min","count"]
)

            mean  max  min  count
Department
AI          88.0   99   76      3
DS          83.0   94   72      2
ML          86.0   88   82      3

## transform()

### DEFINITION:
transform() is a Pandas function that performs a calculation on each group and returns results with the same number of rows as the original data.

#### EXAMPLE:

In [8]:
employees["Department_Average"] = employees.groupby(
    "Department"
)["Marks"].transform("mean")

print(employees)

   Employee_ID     Name Department  Gender  Marks  Age  Department_Average
0          101  Bhaskar         AI    Male     76   22                88.0
1          102     Balu         ML    Male     88   23                86.0
2          103   Baruni         AI  Female     99   21                88.0
3          104  Bhuvesh         DS    Male     94   24                83.0
4          105   Barath         ML    Male     82   22                86.0
5          106  Brindha         DS  Female     72   23                83.0
6          107    Beema         AI  Female     89   21                88.0
7          108   Bushan         ML    Male     88   21                86.0

## filter()

### DEFINITION:
filter() is a Pandas function used with groupby() to select or remove entire groups based on a specified condition.

#### EXAMPLE:

In [9]:
employees.groupby("Department").filter(
    lambda x: x["Marks"].mean() > 90
)

Empty DataFrame
Columns: [Employee_ID, Name, Department, Gender, Marks, Age, Department_Average]
Index: []

## Pivot TABLES

### DEFINITION:

Pivot tables are used to summarize and organize data by grouping rows and columns and applying calculations such as sum, mean, or count.

#### EXAMPLE:

In [11]:
pd.pivot_table(
    employees,
    values="Marks",
    index="Department",
    aggfunc="mean"
)

            Marks
Department
AI           88.0
DS           83.0
ML           86.0

In [12]:
# Multiple Aggregations
pd.pivot_table(
    employees,
    values="Marks",
    index="Department",
    aggfunc=["mean","max","min"]
)

            mean   max   min
           Marks Marks Marks
Department
AI          88.0    99    76
DS          83.0    94    72
ML          86.0    88    82

## CROSSTAB

### DEFINITION:

crosstab() is a Pandas function used to calculate the frequency (count) of combinations between two or more columns.

#### EXAMPLE:

In [13]:
pd.crosstab(
    employees["Department"],
    employees["Gender"]
)

Gender      Female  Male
Department
AI               2     1
DS               1     1
ML               0     3

In [15]:
# Crosstab with Totals
pd.crosstab(
    employees["Department"],
    employees["Gender"],
    margins=True
)

Gender      Female  Male  All
Department
AI               2     1    3
DS               1     1    2
ML               0     3    3
All              3     5    8

In [16]:
# Crosstab with Percentages
pd.crosstab(
    employees["Department"],
    employees["Gender"],
    normalize=True
)

Gender      Female   Male
Department
AI           0.250  0.125
DS           0.125  0.125
ML           0.000  0.375