# **COMBINING DATASETS**

Combining datasets is the process of joining two or more datasets into a single dataset to make data analysis easier. In Python Pandas, concat() and merge() are commonly used for combining datasets.

#### EXAMPLE:
Create Sample Dataset1

In [8]:
import pandas as pd
students = pd.DataFrame({
    'Name': ['Ravi', 'Sita'],
    'Marks': [80, 90],
    'Branch': ['DS', 'ML']
})

print(students)

   Name  Marks Branch
0  Ravi     80     DS
1  Sita     90     ML

#### EXAMPLE:
Create Sample Dataset2

In [3]:
import pandas as pd
Department = pd.DataFrame({
    'Branch': ['AI', 'DS'],
    'Branch_id': [505,707]
})
print(Department)

  Branch  Branch_id
0     AI        505
1     DS        707

#### EXAMPLE:
Create Sample Dataset3

In [6]:
import pandas as pd
new_students = pd.DataFrame({
    'Name': ['Kamala', 'Maharsh'],
    'Branch': ['ML', 'AI'],
    'Marks': [88,99]
})
print(new_students)

      Name Branch  Marks
0   Kamala     ML     88
1  Maharsh     AI     99

## CONCAT()

### DEFINITION:

concat() is a Pandas function used to combine two or more datasets by placing them vertically (rows) or horizontally (columns).

#### EXAMPLE:

In [9]:
combined_students = pd.concat(
    [students, new_students],
    ignore_index=True
)

print(combined_students)

      Name  Marks Branch
0     Ravi     80     DS
1     Sita     90     ML
2   Kamala     88     ML
3  Maharsh     99     AI

In [17]:
children_info = pd.DataFrame({
    "Name": ["Gagan", "Ganga", "Prudvi"],
    "Age": [22, 23, 21]
})

student_scores = pd.DataFrame({
    "Marks": [95, 88, 91],
    "Grade": ["A", "B", "A"]
})

result = pd.concat(
    [children_info, student_scores],
    axis=1
)

print(result)

     Name  Age  Marks Grade
0   Gagan   22     95     A
1   Ganga   23     88     B
2  Prudvi   21     91     A

## MERGE()

### DEFINITION:
merge() is a Pandas function used to combine two datasets based on a common column or key.

#### EXAMPLE:

In [31]:
merged_data = pd.merge(
    students,
    Department,
    on="Branch"
)

print(merged_data)

   Name  Marks Branch  Branch_id
0  Ravi     80     DS        707

Types of Merge
Pandas supports:

* Inner Join
* Left Join
* Right Join
* Outer Join

* **inner join**
* Returns Matching Records.

In [35]:
pd.merge(
    students,
    Department,
    on="Branch",
    how="inner"
)

   Name  Marks Branch  Branch_id
0  Ravi     80     DS        707

* **left join()**

In [37]:
pd.merge(
    students,
    Department,
    on="Branch",
    how="left"
)

   Name  Marks Branch  Branch_id
0  Ravi     80     DS      707.0
1  Sita     90     ML        NaN

* **right join()**

In [41]:
pd.merge(
    students,
    Department,
    on="Branch",
    how="right"
)

   Name  Marks Branch  Branch_id
0   NaN    NaN     AI        505
1  Ravi   80.0     DS        707

* **outer join()**

In [44]:
pd.merge(
    students,
    new_students,
    on="Marks",
    how="outer"
)

  Name_x  Marks Branch_x   Name_y Branch_y
0   Ravi     80       DS      NaN      NaN
1    NaN     88      NaN   Kamala       ML
2   Sita     90       ML      NaN      NaN
3    NaN     99      NaN  Maharsh       AI

## JOIN()

### DEFINITION:

join() is a Pandas method used to combine two datasets based on their index by default. It is useful for bringing related columns together.

In [46]:
student_info = pd.DataFrame({
    "Name": ["Ravi", "Sita", "Prudvi"],
    "Department": ["AI", "ML", "DS"]
}, index=[101, 102, 103])

student_marks = pd.DataFrame({
    "Marks": [95, 88, 91]
}, index=[101, 102, 103])

In [47]:
result = student_info.join(student_marks)

print(result)

       Name Department  Marks
101    Ravi         AI     95
102    Sita         ML     88
103  Prudvi         DS     91

## **append()**

### DEFINITION:
append() is used to add new rows or records to an existing dataset.

Note: In older versions of Pandas, DataFrame.append() was used, but it was removed in Pandas 2.0.

* append() was a Pandas method used to add new rows to an existing DataFrame
* Deprecation of append()
DataFrame.append() was deprecated in Pandas 1.4.0.

It was removed in Pandas 2.0, so the old code will not work in Pandas 2.0 or later.

The recommended alternative is pd.concat().

#### EXAMPLE:

In [49]:
result = pd.concat(
    [students, new_students],
    ignore_index=True
)

print(result)

      Name  Marks Branch
0     Ravi     80     DS
1     Sita     90     ML
2   Kamala     88     ML
3  Maharsh     99     AI

## **combine_first()**

### DEFINITION:
combine_first() is a Pandas method used to combine two datasets by filling missing (NaN) values in the first dataset with corresponding values from the second dataset.

In [52]:
#### EXAMPLE:
student_data1 = pd.DataFrame({
    "Name": ["Amulya", "Rama", "Pardhu"],
    "Marks": [59, None, 87]
})

student_data2 = pd.DataFrame({
    "Name": ["Amruth", "Kushi", "Omkar"],
    "Marks": [None, 88, 92]
})

In [53]:
result = student_data1.combine_first(student_data2)

print(result)

     Name  Marks
0  Amulya   59.0
1    Rama   88.0
2  Pardhu   87.0